version: '3' 

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_webser
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  
  mysql:
    image: mysql:8.0
    container_name: mysql_ver-8
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./db_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: DB_Crawl_News
      MYSQL_USER: turborvip
      MYSQL_PASSWORD: 123456ab
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  
  php:
    build: 
      context: ./php_service/
      dockerfile: PHP.Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - laravel
  
  # composer:
  #   container_name: composer_one
  #   image: composer:latest
  #   command: ["composer", "install"]
  #   volumes:
  #     - ./src:var/www/html
  #   working_dir: /var/www/html
  #   depends_on:
  #     - php
  #   networks:
  #     - laravel

networks:
  laravel:
